### ISSUE TITLE
Fire marker

### ISSUE THREAD

**Issue by dkanou** [ADVRHumanoids/XBotGUI#13]
Ale,

it would be nice to have the same exactly marker tab as the "valve", "door", etc also for the "fire".  Also maybe at some point we add an extra button next to: "Publish marker" and "Position by Click" to have "Detect by vision" or something like that.  We have to think carefully, how do we do that, selecting topics: "laser", "stereo" etc.

Let me know!

**Comment by alessandrosettimi** [comment]
No problem to add these features, please decide what do you want to be the fire related 3d object. Maybe a circle on the ground?

**Comment by dkanou** [comment]
How about a sphere in the 3D space?  Given that the fire will not be on the ground.

**Comment by alessandrosettimi** [comment]
No problem at all.

**Comment by alessandrosettimi** [comment]
In 71fa7379241af50954c05ce161c3fcfdecb6c229 I added another object to the extinguisher tab, this object is a 3d sphere of radius 0.1 m. You can change the properties in the gui xml file (https://github.com/ADVRHumanoids/XBotGUI/blob/master/configs/xbotgui.xml , just look for "fire") if needed.
