### ISSUE TITLE
IM naming

### ISSUE THREAD

**Issue by dkanou** [ADVRHumanoids/XBotGUI#15]
It seems that there is no name specified for different markers as they published from the GUI.

**Comment by alessandrosettimi** [comment]
can you please be more specific? Which name are you talking about? Are you echoing some topic? How can I reproduce the bug?

**Comment by dkanou** [comment]
If you:
> rostopic echo /extinguisher_server/update_full 
you will notice that:
-- server_id: /XBotGUI
-- seq_num: (some increasing number)
-- markers:
    - header:
        seq: 0
        (etc etc)
        name: 0

This name in the markers, can be more specific for each marker we publish?  I am not sure if it is uniquely defined for each marker type, eg. hose, valve, etc

**Comment by alessandrosettimi** [comment]
Well, it is better you take a look at the */extinguisher_client* topic, which is more readable. Since I had to choose a generic way I am using the id as unique identifier of the marker, so each object is idenfied by its topic and id.

Since I am not using the namespace field of the marker, I can use it to write the name of the object (e.g. "fire") to make it more user friendly, would it be ok for you?

**Comment by dkanou** [comment]
Actually you are right.  One can use a subscriber to the client instead.  So no problem.

**Comment by dkanou** [comment]
Sorry @alessandrosettimi 

the extinguisher_client is publishing even when we change the numbers, before pushing "Publish Marker".  Should I open a new issue for that?

**Comment by alessandrosettimi** [comment]
Actually the idea is not to subscribe to the markers topic, instead with @liesrock we provided an interface. See the **ManipulationPlugin** in the xml file, this automatically enable a topic connected to the interactive marker widget.

So if you add e.g.
```
<module name="DIMITRIPlugin">
	<command type="object_pose" topic="DIMITRITopic" interactive_marker="extinguisher"/>
</module>
```
to the file you will have a topic dedicated to your object, this will send a *geometry_msgs/PoseStamped* of the selected object in the widget to the topic *DIMITRITopic* when you click the related button in the GUI (*Send Object Pose* in DIMITRIPlugin tab). Again, in the PoseStamped message there is no name, so if you want I can add a string to the message.

**Comment by dkanou** [comment]
I see.  Ok basically I re-coded a class that takes the markers and produces these Stamped Poses.  Can we already use these method?

**Comment by alessandrosettimi** [comment]
Yes, it is implemented. You just modify the xml file and it's done.

**Comment by dkanou** [comment]
Great!  Thanks!
