### ISSUE TITLE
GUI new plugin dependencies

### ISSUE THREAD

**Issue by pietrobalatti** [ADVRHumanoids/XBotGUI#20]
@alessandrosettimi I am experiencing some problems with the new dependencies. Now when I start the DerbisRemovalTask plugin, automatically all the other plugin start, but this cannot work, since I need to stop the homing before starting the others and I want to make sure that when I start the Debris plugin all the others have already been started. What I would like to have is:

1 tab for HomingExample
1 tab that starts together ManipulationPlugin, IkRosSharedMemoryPublisher and OpenSotIk
1 tab that just starts the DebrisRemovalTask

Maybe the second and the third tab can be collapsed, BUT only if you make sure the order in which they are started is the one stated above (so the debris task must be the last one).

Thank you.
Best,
Pietro

**Comment by alessandrosettimi** [comment]
I see, of course DerbisRemovalTask and HomingExample cannot run together, I didn't think about this. However I imposed an order for starting the plugins. Can you pull and test?

**Comment by pietrobalatti** [comment]
Now it's working but I still need to start the ManipulationPlugin (with OpenSotIk included) and the IkRosSharedMemoryPublisher in two different tabs.

**Comment by alessandrosettimi** [comment]
Since I can't test in gazebo (keeps crashing) can you tell me which output the gui generates in the terminal if you just open it and click on the start button of the DebrisRemovalTask tab?

**Comment by pietrobalatti** [comment]
If you mean, without starting the Homing and the other ones,  if you just starting the DebrisRemovalTask this is the output

```
Starting plugin : OpenSotIk
OpenSotIkTestPlugin STARTED!
Initial q is            0            0      1.04775  6.93889e-18  1.11022e-16            0 -0.000229082  -0.00451985  -0.00255783 -5.51238e-07  -0.00344129   0.00013753  0.000152559   0.00344338  -0.00307932 -1.97052e-05  -0.00298652 -0.000165377  6.04824e-05   0.00100789  5.55665e-05 -0.000704228    0.0872508   7.4336e-05  -0.00140339 -0.000165652  6.27271e-05 -0.000959606 -6.06973e-05  -0.00121462 -0.000326146    -0.121955 -5.47973e-05  -0.00139518   6.7581e-05  8.65712e-05   0.00090146
Home q is           0           0     1.04775 6.93889e-18 1.11022e-16           0       -0.06           0       -0.45         0.9       -0.45        0.06        0.06           0       -0.45         0.9       -0.45       -0.06           0           0           0         1.1         0.2        -0.3          -2           0           0          -0           0         0.6         1.1        -0.2         0.3          -2           0          -0          -0
Starting plugin : DebrisRemovalTask
Homing_entry
Homing run
```

**Comment by alessandrosettimi** [comment]
Actually I mean the output in the GUI terminal, where you start it.

**Comment by pietrobalatti** [comment]
```
 >> Started XBotGUI for robot bigman <<

[ /ManipulationPlugin_switch STARTED ]
[ /OpenSotIk_switch STARTED ]
[ /DebrisRemovalTask_switch STARTED ]
```

**Comment by alessandrosettimi** [comment]
Maybe I got it. Basically the *IkRosSharedMemoryPublisher* changed its name in the **walkman_sprintweek_2** branch of **ADVR_SHARED** to *IkRosSMPub*. In the GUI config file I wrote "IkRosSMPub" as depencency for the debris plugin, if you change to "IkRosSharedMemoryPublisher" it should work.

However, @liesrock, what is the real name of this plugin? :smile:

**Comment by alessandrosettimi** [comment]
So, *IkRosSMPub* is the correct name. I close this.
