### ISSUE TITLE
Use plugin status to manage active commands

### ISSUE THREAD

**Issue by alessandrosettimi** [ADVRHumanoids/XBotGUI#22]
so we can enable/disable or show/not show some commands depending on the plugin status

**Comment by alessandrosettimi** [comment]
done in 8a8d4ad047d269cec78d0f2f6eb9f35213c34cb0. @pietrobalatti you can use this feature like this:

`<command type="cmd_service" name="homing_success" enabling_status="Running : TEST"/>`

If you do not add any enabling_status the button will always be active.

**Comment by pietrobalatti** [comment]
done in 3f76c7cdf38180bfa13340757fd6b5e505448c76. Everything works fine, thanks @alessandrosettimi!

**Comment by alessandrosettimi** [comment]
super!
