### ISSUE TITLE
More enabling status for one button

### ISSUE THREAD

**Issue by pietrobalatti** [ADVRHumanoids/XBotGUI#36]
Hi @alessandrosettimi,

would it be possible to put in OR more than one "enabling_status" for a single "cmd_service" so that they can be active on more than one state and they can be reused? This would help the shrinking of the GUI.
Thanks!

Pietro

**Comment by alessandrosettimi** [comment]
Seems reasonable! I will do it asap.

**Comment by alessandrosettimi** [comment]
Done in 45ee4ef2321ff34329b8630f571e2d29732ddff9. You can have multiple enabling status by listing them, and separating them with a space.

Example:
```
<command type="cmd_service" name="homing_success_valve" enabling_status="RUNNING:HOMING RUNNING:OTHER"/>
```

**Comment by pietrobalatti** [comment]
Thank you @alessandrosettimi!
