### ISSUE TITLE
Add basic Walking commands

### ISSUE THREAD

**Issue by liesrock** [ADVRHumanoids/XBotGUI#39]
We would like to have a command interface in the GUI for the chengxu walking plugin with the following requirements: 

- Adjust step lenght
- Go forward X m
- Go backward X m
- Go left X m
- Go right X m
- Turn clockwise by X deg
- Turn counterclockwise by X deg

Would it be possible (Similar to the old DRC interface)?

**Comment by alessandrosettimi** [comment]
We can do it easily, I will start asap.

**Comment by alessandrosettimi** [comment]
I'm working on the graphical side, meanwhile, can you tell me which kind of service/topic will be related to this commands? If you want I can add a service in ADVR_ROS made by a string and a number.

**Comment by liesrock** [comment]
This would be great!

**Comment by alessandrosettimi** [comment]
I think we have it.

See c0d64e91a39cd823f47167e3a62db11fa73c75de and https://github.com/ADVRHumanoids/ADVR_ROS/commit/3cbd9dd6ddfabf3c4f6608cde97628ff314991d6 .

**Comment by liesrock** [comment]
ok @alessandrosettimi thanks! So if I have understood correctly I have to create a service called /walking_command currently that will receive/send the srv defined in advr_locomotion.srv right?
From the GUI point of view @czhoucc was asking a feedback about the last command sent (e.g. you sent go forward 0.2 m with a step_length of 0.1): is it feasible?

**Comment by alessandrosettimi** [comment]
Yes, you have to make a service server in the walking module.

Yes, it is possible indeed, I will make a scrollable log in the walking widget.

**Comment by liesrock** [comment]
Ok, the integration is almost done: I will use an int to represent the cmd_type (RT-safe and no mutex needed).

walk_forward -> 1
walk_forward -> 1
walk_forward -> 1

**Comment by liesrock** [comment]
I will update the GUI accordingly!

**Comment by alessandrosettimi** [comment]
ok thanks!

**Comment by liesrock** [comment]
ok done! If you pull latest master of XBotGUI and ADVR_ROS you will have the modification.

**Comment by czhoucc** [comment]
Hi, @alessandrosettimi 
we need one more button for sending a char to the plugin.
Let's call it "Execute" , and by default, the char value is 'c'.

**Comment by liesrock** [comment]
@alessandrosettimi should we update also the ROS srv?

**Comment by alessandrosettimi** [comment]
Yes please

**Comment by liesrock** [comment]
I take care of it, and I update also chengxu_walking code accordingly: let me know the the GUI is ready from your side!

**Comment by liesrock** [comment]
ok done for ADVR_ROS and chengxu_walking

**Comment by liesrock** [comment]
@alessandrosettimi any news on the GUI?

**Comment by alessandrosettimi** [comment]
I implemented the Execute button in cc04eff8589077d3d243b3dd9a4bf74d6876e4b8. Now when sending commands, Execute button will call the service with command=0 and execure='c', while when using the other buttons the service is called with command following the scheme @liesrock explained above and execute =' '

Is this ok? @liesrock I remember you talk about a list of sent commands.

**Comment by czhoucc** [comment]
@alessandrosettimi 
could you please also add a textbox with the default value 'c' next to the Execute button? Therefore we can also send other characters except 'c' by changing this textbox to the plugin.

**Comment by czhoucc** [comment]
@alessandrosettimi 
Perfect! Tested working. Thank you very much

**Comment by alessandrosettimi** [comment]
super!
