### ISSUE TITLE
GUI closing not working

### ISSUE THREAD

**Issue by pietrobalatti** [ADVRHumanoids/XBotGUI#42]
CTRL+C is always intercepted by the GUI (red message in the terminal) but then it gets almost always stuck there and I need to close it sending "killall XBotGUI -9" from another terminal.

Could it be an idea to send this killall command when this keys combination is intercepted? I don't know if it is even possible or if it is a too "dirty" solution, it's just my two cents.

**Comment by alessandrosettimi** [comment]
This is not happening on my machine, does this happen to you always? Simple test: run it, do nothing, then CTRL+C.

**Comment by pietrobalatti** [comment]
No not always, if I close it at the beginning it works (probably there are not a lot of things going on). If I am in the middle of the task it gets stuck..

**Comment by alessandrosettimi** [comment]
The next time this issue appear, please write here what exactly you were doing. I think it is some thread waiting some something that freeze the kill.

The solution of putting "killall" inside the gui is super-dirty :laughing:

**Comment by pietrobalatti** [comment]
I think we solved it, so basically the GUI was running on all the available cores and this was causing problems. It was enough to make it run just on one core by setting:

```cpp
taskset -c 0 XBotGUI
```
and now it is much lighter!

**Comment by alessandrosettimi** [comment]
A greedy GUI :)

**Comment by pietrobalatti** [comment]
Super greedy ?

Il giorno 31 gen 2018, alle ore 18:51, Alessandro Settimi <notifications@github.com<mailto:notifications@github.com>> ha scritto:


A greedy GUI :)

-
