### ISSUE TITLE
No point clouds in GUI

### ISSUE THREAD

**Issue by dkanou** [ADVRHumanoids/XBotGUI#47]
Ale,

I am not able to see the point cloud in the GUI.  Can you check if the topics are correct (changed bigman to walkman when needed, etc)?

Just to be sure: I press the /multisense/left_camera_optical_frame and then I press to see the point_cloud.  Right?

**Comment by alessandrosettimi** [comment]
Well, point cloud inXBotGUI is working (tested on my pc with a rosbag file).

If you select */multisense/left_camera_optical_frame* you should also avoid the TF usual problems. Then you do not need to press anything to see the cloud. Is it working in RViz?

bigman/walkman switch does not change topics name.

**Comment by dkanou** [comment]
Hi Ale,

I think it is a robot issue.  We try to solve it.  I leave the issue open, but probably will close it soon since it does not seem to be a GUI problem!  Thanks!
